# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'dotp_client' do
  pod 'Locksmith'
end

target 'dotp_clientTests' do

end

